const Works = [    
    {
        id: 1,
        name: "Portfolio",
        description: "The website you are navigation on :)",
        type: "web",
        url: "",
        html: "./assets/html5.png",
        css: "./assets/css3.png",
        bootstrap:"",
        js: "./assets/javascript.png",
        react: "./assets/react.png",
        node: "./assets/nodejs.png",
        wordpress: "",
        photoshop:"",
        github: "./assets/github.png"        
    },
    {
        id: 2,
        name: "SJOC Website",
        description: "Designed and developed company's website in HTML, CSS, JS, and WordPress",
        type: "web",
        url: "https://lucassacheto.me/lucassacheto/sjoc",        
        html: "./assets/html5.png",
        css: "./assets/css3.png",
        bootstrap: "./assets/bootstrap.png",
        js: "./assets/javascript.png",
        react: "",
        node: "",
        wordpress: "./assets/wordpress.png",        
        photoshop: "./assets/photoshop.png",
        github: "./assets/github.png"
    },
    {
        id: 3,
        name: "Personal Blog",
        description: "Personal blog built in WordPress using HTML, CSS and VanillaJS",
        type: "web",
        url: "https://lucassacheto.me/lucassacheto/wp_template/",
        html: "./assets/html5.png",
        css: "./assets/css3.png",
        js: "./assets/javascript.png",
        react:"",
        node:"",        
        wordpress: "./assets/wordpress.png",
        photoshop:"",
        github: "./assets/github.png"
    },
    {
        id: 4,
        name: "Robo Friends",
        description: "Single page application in React and JSON listing robots via API using input filter",
        type: "app",
        url: "https://lucassacheto.me/lucassacheto/robofriends",
        html: "./assets/html5.png",
        css: "./assets/css3.png",
        js: "./assets/javascript.png",
        react: "",
        node:"",        
        wordpress: "",
        photoshop:"",
        github: "./assets/github.png"
    },
    {
        id: 5,
        name: "Tax Calculator",
        description: "Canadian Tax Calculator build in React",
        type: "app",
        url: "https://lucassacheto.me/lucassacheto/tax-calculator",
        html: "./assets/html5.png",
        css: "./assets/css3.png",
        js: "./assets/javascript.png",
        react: "./assets/react.png",
        node:"",
        wordpress: "",
        photoshop:"",
        github: "./assets/github.png"
    }
]

export default Works;